
replicaCount: 3
namespace: server

image:
  repository: jackrooty/server
  pullPolicy: IfNotPresent
  tag: "latest"

# If repo is private - uncomment block in deployment.yaml template
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
